"""The reverse reasoning tree, filmed as a README artifact.

Generated by driving the Mythos chain on one request:

    "Animate the reverse reasoning tree from the README. This is a README
     artifact, so keep every label large and legible: decompose the question
     backward to known ground, then walk it forward as a curriculum."

The cartographer fixed the tree, the cinematographer scored the beats, and the
scene-composer laid it out in the Mythos house style (dark stage, glow nodes,
gold forward-pulse). Unlike the flagship cut, this one stays top-down the whole
way so the text never tilts out of read -- it is meant to be paused and read on
the page it lives on.

Render:
    manim -qm --format=gif examples/mythos/readme_reverse_tree.py ReadmeReverseTree
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from manim import (  # noqa: E402
    DOWN,
    LEFT,
    RIGHT,
    UP,
    ORIGIN,
    Create,
    FadeIn,
    FadeOut,
    Indicate,
    LaggedStart,
    Line,
    RoundedRectangle,
    Text,
    ThreeDScene,
    VGroup,
)

from mythos.cinematography import (  # noqa: E402
    CORAL,
    FOG,
    GOLD,
    INK,
    IVORY,
    OLIVE,
    SKY,
    caption,
    clear_caption,
    headline,
    stage,
    starfield,
)


def _fit(text: Text, max_w: float) -> Text:
    if text.width > max_w:
        text.set(width=max_w)
    return text


class ReadmeReverseTree(ThreeDScene):
    """Backward to known ground, then forward as a curriculum -- readably."""

    def node(self, label, center, color, w, h, fs, weight="NORMAL"):
        box = RoundedRectangle(
            width=w, height=h, corner_radius=min(0.22, h / 2 - 0.02),
            stroke_color=color, stroke_width=3, fill_color=INK, fill_opacity=0.92,
        ).move_to(center)
        halo = RoundedRectangle(
            width=w, height=h, corner_radius=min(0.22, h / 2 - 0.02),
            stroke_color=color, stroke_width=11, fill_opacity=0,
        ).move_to(center).set_stroke(opacity=0.16)
        text = _fit(Text(label, font_size=fs, color=IVORY, weight=weight,
                         line_spacing=0.7), w - 0.35)
        text.move_to(center)
        return VGroup(halo, box, text)

    def edge(self, a, b, color=FOG, width=2.2, op=0.7):
        return Line(a[1].get_bottom(), b[1].get_top(),
                    color=color, stroke_width=width, stroke_opacity=op)

    def edge_to(self, a, point, color=FOG, width=2.2, op=0.7):
        return Line(a[1].get_bottom(), point, color=color,
                    stroke_width=width, stroke_opacity=op)

    def construct(self):
        stage(self)
        stars = starfield(n=110, z=0.0, seed=11)
        stars.set_opacity(0.22)
        self.add(stars)

        headline(
            self,
            "Ask a question. Get a film.",
            sub="But first -- what must a mind already know?",
            accent=CORAL,
            hold=1.3,
        )

        # ---- nodes, faithful to the README chart ----------------------- #
        root = self.node("Explain quantum field theory", [0, 3.35, 0],
                         CORAL, 5.4, 0.95, 30, weight="BOLD")

        sr = self.node("special relativity", [-3.5, 1.85, 0], SKY, 3.3, 0.8, 26)
        qm = self.node("quantum mechanics", [3.5, 1.85, 0], SKY, 3.3, 0.8, 26)

        si = self.node("spacetime\nintervals", [-5.35, 0.3, 0], OLIVE, 2.55, 0.95, 22)
        li = self.node("Lorentz\ninvariance", [-2.2, 0.3, 0], OLIVE, 2.55, 0.95, 22)
        wf = self.node("wavefunctions", [2.2, 0.3, 0], OLIVE, 2.55, 0.95, 22)
        op = self.node("operators", [5.35, 0.3, 0], OLIVE, 2.55, 0.95, 22)

        sp = self.node("superposition", [2.2, -1.25, 0], FOG, 2.55, 0.8, 21)
        cm = self.node("commutation", [5.35, -1.25, 0], FOG, 2.55, 0.8, 21)

        ground = self.node("the tree bottoms out at known ground",
                           [0, -2.6, 0], GOLD, 8.6, 0.8, 24, weight="BOLD")

        # edges of the backward decomposition
        e_root = [self.edge(root, sr, SKY, 2.6, 0.85),
                  self.edge(root, qm, SKY, 2.6, 0.85)]
        e_sr = [self.edge(sr, si), self.edge(sr, li)]
        e_qm = [self.edge(qm, wf), self.edge(qm, op)]
        e_leaf = [self.edge(wf, sp), self.edge(op, cm)]

        gtop = ground[1].get_top()
        e_ground = [
            self.edge_to(si, gtop + LEFT * 3.4, OLIVE, 2.0, 0.6),
            self.edge_to(li, gtop + LEFT * 1.2, OLIVE, 2.0, 0.6),
            self.edge_to(sp, gtop + RIGHT * 1.2, OLIVE, 2.0, 0.6),
            self.edge_to(cm, gtop + RIGHT * 3.4, OLIVE, 2.0, 0.6),
        ]

        # ---- build it backward ----------------------------------------- #
        self.play(FadeIn(root, shift=DOWN * 0.3), run_time=0.8)
        caption(self, "The engine reasons backward from the target...",
                color=CORAL, hold=0.3)

        self.play(
            LaggedStart(*[Create(e) for e in e_root], lag_ratio=0.25),
            LaggedStart(*[FadeIn(n, shift=DOWN * 0.2) for n in (sr, qm)],
                        lag_ratio=0.25),
            run_time=1.3,
        )
        caption(self, "...asking of each answer: what must you already know?",
                color=SKY, hold=0.5)
        self.play(
            LaggedStart(*[Create(e) for e in e_sr + e_qm], lag_ratio=0.15),
            LaggedStart(*[FadeIn(n, shift=DOWN * 0.2) for n in (si, li, wf, op)],
                        lag_ratio=0.15),
            run_time=1.5,
        )
        self.play(
            LaggedStart(*[Create(e) for e in e_leaf], lag_ratio=0.2),
            LaggedStart(*[FadeIn(n, shift=DOWN * 0.2) for n in (sp, cm)],
                        lag_ratio=0.2),
            run_time=1.2,
        )

        # ---- bottom out at known ground -------------------------------- #
        self.play(
            LaggedStart(*[Create(e) for e in e_ground], lag_ratio=0.12),
            FadeIn(ground, shift=UP * 0.15),
            run_time=1.5,
        )
        caption(self, "...until every leaf is something the viewer already holds.",
                color=GOLD, hold=1.3)

        # ---- now walk it FORWARD --------------------------------------- #
        clear_caption(self)
        caption(self, "Now walk it forward -- as a curriculum.",
                color=GOLD, hold=1.0)
        # the strip lives at the bottom edge, where captions sit -- clear first
        clear_caption(self)

        forward = VGroup()
        stages = ["known ground", "prerequisites", "target concept", "the film"]
        # Build the forward strip as discrete, sequentially-lit stages.
        xs = [-4.7, -1.6, 1.5, 4.7]
        pills = []
        for i, (s, x) in enumerate(zip(stages, xs)):
            last = i == len(stages) - 1
            pill = self.node(s, [x, -3.5, 0], GOLD if last else FOG,
                             2.9 if len(s) > 11 else 2.5, 0.72,
                             22 if last else 20, weight="BOLD" if last else "NORMAL")
            pills.append(pill)
            forward.add(pill)
        arrows = []
        for i in range(len(pills) - 1):
            a = Text("→", font_size=30, color=GOLD)
            a.move_to((pills[i][1].get_right() + pills[i + 1][1].get_left()) / 2)
            arrows.append(a)
            forward.add(a)

        self.play(FadeIn(pills[0], shift=UP * 0.1), run_time=0.5)
        for i in range(1, len(pills)):
            self.play(
                FadeIn(arrows[i - 1]),
                FadeIn(pills[i], shift=RIGHT * 0.15),
                pills[i - 1][2].animate.set_color(GOLD),
                run_time=0.55,
            )
        self.play(Indicate(pills[-1], color=GOLD, scale_factor=1.12), run_time=0.9)
        self.wait(0.5)

        # ---- final title ------------------------------------------------ #
        clear_caption(self)
        whole = VGroup(root, sr, qm, si, li, wf, op, sp, cm, ground, forward,
                       *e_root, *e_sr, *e_qm, *e_leaf, *e_ground)
        self.play(FadeOut(whole), stars.animate.set_opacity(0.12), run_time=1.0)
        headline(
            self,
            "Six agents. One film.",
            sub="intent · cartographer · curriculum · math-director · cinematographer · scene-composer",
            accent=GOLD,
            hold=1.9,
        )
        self.wait(0.3)
