"""The Sound of Spacetime — a Mythos film.

Gravitational waves, from Einstein's field equations to the morning LIGO
heard two black holes collide. Generated by the six-agent Mythos chain
(intent -> cartographer -> curriculum -> math director -> cinematographer ->
scene composer); run artifacts in runs/mythos/20260703-165603-*.

Render:
    manim -ql examples/mythos/sound_of_spacetime.py TheSoundOfSpacetimeJourney
    manim -qh examples/mythos/sound_of_spacetime.py TheSoundOfSpacetimeJourney
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from manim import *

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from mythos.cinematography import (  # noqa: E402
    CORAL, EMBER, FOG, GOLD, INK, IVORY, OLIVE, SKY,
    caption, glow, glow_dot, headline, orbit, stage, starfield,
)

DARK_A = "#1c1410"
DARK_B = "#151009"
WAVE_A = "#0e1622"
WAVE_B = "#0a1119"
OLIVE_BRIGHT = "#a8bd8a"

# Chirp waveform constants (inspiral-merger-ringdown)
T_M, TAU_R, F_R = 0.82, 0.045, 26.0


def chirp_y(t: float) -> float:
    """Strain h(t): amplitude and frequency ramp, merger spike, damped ringdown."""
    if t <= T_M:
        amp = 0.12 + 1.05 * (t / T_M) ** 3
        phase = TAU * (3.5 * t + 8.5 * t ** 3)
        return amp * np.sin(phase)
    a_pk = 1.17
    phase_m = TAU * (3.5 * T_M + 8.5 * T_M ** 3)
    return a_pk * np.exp(-(t - T_M) / TAU_R) * np.sin(phase_m + TAU * F_R * (t - T_M))


def _rx(p, a):
    x, y, z = p
    return np.array([x, y * np.cos(a) - z * np.sin(a), y * np.sin(a) + z * np.cos(a)])


class TheSoundOfSpacetimeJourney(ThreeDScene):
    """~140 s. Camera rule: move_camera only — never .animate on the camera."""

    def construct(self):
        stage(self)
        self.act1_fabric()
        self.act2_bend()
        self.act3_waltz()
        self.act4_law()
        self.act5_stiffness()
        self.act6_chirp()
        self.act7_morning()

    # ------------------------------------------------------------------ #
    # Act 1 — The Fabric Beneath the Stars (20 s)                         #
    # ------------------------------------------------------------------ #

    def act1_fabric(self):
        # Beat 1 — starfield drifts up out of black
        self.stars = starfield(n=180)
        target_ops = [np.random.uniform(0.25, 0.95) for _ in self.stars]
        self.stars.set_opacity(0)
        self.add(self.stars)
        self.play(
            LaggedStart(*[s.animate.set_opacity(o) for s, o in zip(self.stars, target_ops)],
                        lag_ratio=0.01),
            run_time=2.5,
        )

        # Beat 2 — the apple: the one thing everyone already knows
        rail = DashedLine([0, 2.6, 0], [0, -1.4, 0], color=FOG,
                          stroke_width=2, dash_length=0.12)
        apple = Circle(radius=0.2, fill_color=IVORY, fill_opacity=1.0,
                       stroke_width=0).move_to([0, 2.6, 0])
        stem = Line(ORIGIN, [0.05, 0.12, 0], color=FOG, stroke_width=2)
        stem.move_to(apple.get_top() + np.array([0.03, 0.05, 0]))
        fruit = VGroup(apple, stem)
        self.play(FadeIn(rail), FadeIn(fruit), run_time=0.8)
        self.play(fruit.animate.shift(DOWN * 4.0), run_time=2.2,
                  rate_func=rate_functions.ease_in_quad)

        # Beat 3 — darkness holds
        self.wait(0.6)
        self.play(FadeOut(rail), FadeOut(fruit), run_time=0.4)

        # Beat 4 — headline
        headline(self, "Space is not empty. It is a fabric.", hold=1.4)

        # Beats 5-6 — the fabric fades up beneath the stars; tilt into 3D
        self.t_breath = ValueTracker(0.0)
        self.amp = ValueTracker(0.08)
        self.dimple = ValueTracker(0.0)
        self.hump = ValueTracker(0.0)
        self.tau = ValueTracker(0.0)
        self.fab_fade = ValueTracker(0.0)
        self.t_breath.add_updater(lambda m, dt: m.increment_value(dt))

        def fabric_z(u, v):
            tb = self.t_breath.get_value()
            z = self.amp.get_value() * np.sin(0.7 * u + 0.9 * tb) * np.cos(0.7 * v + 0.6 * tb)
            d = self.dimple.get_value()
            if d > 1e-3:
                z += -1.4 * d / (np.hypot(u, v) + 0.7)
            h = self.hump.get_value()
            if h > 1e-3:
                cx = -5 + 10 * self.tau.get_value()
                z += h * np.exp(-((u - cx) ** 2 + (v - cx) ** 2) / 0.9)
            return z

        self._fabric_z = fabric_z

        def make_fabric():
            f = self.fab_fade.get_value()
            s = Surface(
                lambda u, v: np.array([u, v, fabric_z(u, v)]),
                u_range=[-6, 6], v_range=[-6, 6], resolution=(28, 28),
                fill_opacity=0.35 * f, checkerboard_colors=[DARK_A, DARK_B],
            )
            s.set_stroke(CORAL, width=0.8, opacity=0.85 * f)
            return s

        self.fabric = always_redraw(make_fabric)
        self.add(self.fabric)
        self.add(self.t_breath)  # keep the breath ticking through every play
        self.play(self.fab_fade.animate.set_value(1.0), run_time=1.5)
        self.move_camera(phi=60 * DEGREES, theta=-45 * DEGREES, zoom=0.9, run_time=2.5)
        orbit(self, rate=0.05, duration=2.6)

        # Beat 7 — caption
        caption(self, "Not a void — a surface, catching light.", hold=1.4)

        # Beat 8 — the grid flexes once, almost imperceptibly
        self.play(self.amp.animate.set_value(0.16), run_time=0.5)
        self.play(self.amp.animate.set_value(0.08), run_time=0.5)

    # ------------------------------------------------------------------ #
    # Act 2 — The Bend (17 s)                                             #
    # ------------------------------------------------------------------ #

    def act2_bend(self):
        # Beat 9
        headline(self, "Mass bends the fabric. That bending is gravity.", hold=1.0)

        # Beat 10 — the mass appears above the grid, gold halo
        self.mass = Sphere(radius=0.35, resolution=(18, 18),
                           checkerboard_colors=[IVORY, "#e8e6df"],
                           fill_opacity=1.0).move_to([0, 0, 0.8])
        self.mass_halo = glow_dot(point=[0, 0, 0.8], color=GOLD, radius=0.12, layers=5)
        self.mass_halo.add_updater(lambda m: m.move_to(self.mass.get_center()))
        self.play(FadeIn(self.mass), FadeIn(self.mass_halo), run_time=2.0)

        # Beat 11 — the sink: grid dimples as the mass settles (seen, not cut to)
        self.play(self.dimple.animate.set_value(1.0),
                  self.mass.animate.move_to([0, 0, -1.55]), run_time=3.5)

        # Beat 12 — slow orbit of the dimple
        orbit(self, rate=0.06, duration=2.0)

        # Beat 13 — the mote falls without being pulled
        def mote_point(t):
            r = 4.5 - 2.8 * t
            th = PI / 4 + 1.9 * t
            return np.array([r * np.cos(th), r * np.sin(th), -1.4 / (r + 0.7) + 0.06])

        mote_rail = ParametricFunction(mote_point, t_range=[0, 1], stroke_width=0)
        self.mote = glow_dot(point=mote_point(0), color=SKY, radius=0.05, layers=5)
        self.play(FadeIn(self.mote), run_time=0.3)
        self.play(MoveAlongPath(self.mote, mote_rail), run_time=2.7, rate_func=linear)

        # Beat 14 — the apple ghost: this is what that was, all along
        ghost = Circle(radius=0.1, fill_color=IVORY, fill_opacity=0.35, stroke_width=0)
        ghost.to_corner(UL, buff=1.0)
        self.add_fixed_in_frame_mobjects(ghost)
        ghost.set_opacity(0)
        self.play(ghost.animate.set_opacity(0.35), run_time=0.25)
        self.play(FadeOut(ghost), run_time=0.25)

        # Beats 15-16
        caption(self, "Falling is just following a bent line.", hold=1.4)
        self.wait(1.0)

    # ------------------------------------------------------------------ #
    # Act 3 — The Doomed Waltz (21 s)                                     #
    # ------------------------------------------------------------------ #

    def act3_waltz(self):
        # Beat 17 — headline; the mass leaves behind it
        headline(self, "A fabric that bends can also shake.", hold=0.7)

        # Beat 18 — the flick: dimple relaxes, one hump of light crosses the sheet
        self.mass_halo.clear_updaters()
        self.speck = glow_dot(point=[4.5, 4.5, 0.02], color=IVORY, radius=0.05, layers=4)
        self.speck.add_updater(
            lambda m: m.move_to([4.5, 4.5, self._fabric_z(4.5, 4.5) + 0.02]))
        self.hump.set_value(0.55)
        old_cap = getattr(self, "_mythos_caption", None)
        cap_out = [FadeOut(old_cap)] if old_cap is not None else []
        self._mythos_caption = None
        self.play(FadeOut(self.mass), FadeOut(self.mass_halo), FadeOut(self.mote),
                  FadeIn(self.speck), self.dimple.animate.set_value(0.0),
                  *cap_out, run_time=0.7)
        self.play(self.tau.animate.set_value(1.0), run_time=2.8, rate_func=linear)

        # Beat 19 — the speck settles
        self.hump.set_value(0.0)
        self.wait(0.8)
        self.speck.clear_updaters()

        # Beat 20 — tilt up to the waltz: two black spheres, spiral wakes
        self.R_orb = ValueTracker(2.2)
        self.th_orb = ValueTracker(0.0)
        self.tau_w = ValueTracker(0.0)
        self.wave_fade = ValueTracker(0.0)
        self._tau_rate = 1.0
        self.tau_w.add_updater(lambda m, dt: m.increment_value(self._tau_rate * dt))
        self.th_orb.add_updater(
            lambda m, dt: m.increment_value(
                dt * min(1.6 * (2.2 / max(self.R_orb.get_value(), 0.4)) ** 1.5, 12.0)))
        self.add(self.tau_w, self.th_orb)

        bh1 = Sphere(radius=0.45, resolution=(16, 16),
                     checkerboard_colors=["#050505", "#0b0b0a"], fill_opacity=1.0)
        bh2 = Sphere(radius=0.38, resolution=(16, 16),
                     checkerboard_colors=["#050505", "#0b0b0a"], fill_opacity=1.0)
        for s in (bh1, bh2):  # kill the default pale mesh: black holes are voids
            s.set_stroke("#141414", width=0.4, opacity=0.5)
        rim1 = Circle(radius=0.51, stroke_color=SKY, stroke_width=6, stroke_opacity=0.35)
        rim2 = Circle(radius=0.44, stroke_color=SKY, stroke_width=6, stroke_opacity=0.35)

        def bh_place(_):
            r = self.R_orb.get_value()
            th = self.th_orb.get_value()
            p1 = np.array([r * np.cos(th), r * np.sin(th), 0.12])
            p2 = np.array([-0.85 * r * np.cos(th), -0.85 * r * np.sin(th), 0.12])
            bh1.move_to(p1)
            rim1.move_to(p1)
            bh2.move_to(p2)
            rim2.move_to(p2)

        self.binary = VGroup(bh1, rim1, bh2, rim2)
        self._bh_place = bh_place
        bh_place(None)
        self.binary.add_updater(bh_place)

        def make_waves():
            tw = self.tau_w.get_value()
            f = self.wave_fade.get_value()
            s = Surface(
                lambda r, ph: np.array([
                    r * np.cos(ph), r * np.sin(ph),
                    0.35 * np.sin(3.0 * r - 2.4 * tw + 2 * ph) / (r + 1),
                ]),
                u_range=[0.6, 7.0], v_range=[0, TAU], resolution=(24, 48),
                fill_opacity=0.28 * f, checkerboard_colors=[WAVE_A, WAVE_B],
            )
            s.set_stroke(SKY, width=0.6, opacity=0.7 * f)
            return s

        self.waves = always_redraw(make_waves)
        self.add(self.waves, self.binary)
        self.move_camera(
            phi=65 * DEGREES, theta=30 * DEGREES, zoom=0.85, run_time=3.5,
            added_anims=[self.wave_fade.animate.set_value(1.0),
                         self.fab_fade.animate.set_value(0.0),
                         FadeOut(self.speck)],
        )
        self.remove(self.fabric)
        self.t_breath.clear_updaters()

        # Beat 21 — ambient orbit of the waltz
        orbit(self, rate=0.08, duration=3.0)

        # Beats 22-23
        headline(self, "The ripples carry energy away — so the orbit is doomed.",
                 hold=0.5, font_size=64)
        caption(self, "Each spiral of light is stolen orbital energy.", hold=1.9)

        # Beat 24 — the circle tightens: doom made continuous
        self.play(self.R_orb.animate.set_value(1.4), run_time=2.7)

    # ------------------------------------------------------------------ #
    # Act 4 — The Law (19 s)                                              #
    # ------------------------------------------------------------------ #

    def act4_law(self):
        # Beat 25 — the waltz freezes; gallery-dark flat stage
        self._tau_rate = 0.0
        self.binary.clear_updaters()
        cap = getattr(self, "_mythos_caption", None)
        extra = [FadeOut(cap)] if cap is not None else []
        self._mythos_caption = None
        self.move_camera(
            phi=0 * DEGREES, theta=-90 * DEGREES, zoom=1.0, frame_center=ORIGIN,
            run_time=1.5,
            added_anims=[FadeOut(self.binary), self.wave_fade.animate.set_value(0.0),
                         self.stars.animate.set_opacity(0.15)] + extra,
        )
        self.remove(self.waves)

        # Beat 26
        headline(self, "One equation connects matter to the shape of space.",
                 hold=1.0, font_size=64)

        # Beat 27 — the field equation, hung in gallery light
        self.efe = MathTex("G_{\\mu\\nu}", "=", "\\frac{8\\pi G}{c^{4}}",
                           "T_{\\mu\\nu}").scale(1.5)
        self._efe_colors = [CORAL, IVORY, OLIVE, GOLD]
        for part, col in zip(self.efe, self._efe_colors):
            part.set_color(col)
        self.play(Write(self.efe), run_time=2.5)

        # Beat 28
        caption(self, "Geometry on the left. Matter and energy on the right.", hold=1.4)

        # Beats 29-32 — the term tour: constant zoom 2.0, panning stop to stop
        stops = [
            (0, CORAL, "How the fabric bends — the geometry of spacetime, point by point."),
            (1, GOLD, "Reads as 'is decided by' — a law, not a suggestion."),
            (2, OLIVE, "The exchange rate between energy and bending — fantastically small."),
            (3, GOLD, "Everything matter and energy are doing in this patch of universe."),
        ]
        frame = None
        for idx, col, words in stops:
            part = self.efe[idx]
            new_frame = SurroundingRectangle(part, color=col, buff=0.12, stroke_width=2.5)
            anims = [Create(new_frame)]
            anims += [p.animate.set_opacity(0.3) for p in self.efe if p is not part]
            anims.append(part.animate.set_opacity(1.0))
            if frame is not None:
                anims.append(FadeOut(frame))
            self.move_camera(frame_center=part.get_center(), zoom=2.0,
                             run_time=0.8, added_anims=anims)
            caption(self, words, color=col, hold=0.6)
            frame = new_frame

        # Beat 33 — pull back: the part within the whole
        self.move_camera(frame_center=ORIGIN, zoom=1.0, run_time=1.0,
                         added_anims=[FadeOut(frame),
                                      self.efe.animate.set_opacity(1.0)])

        # Beat 34 — everything dims to embers except the fraction
        self.play(*[self.efe[i].animate.set_color(EMBER).set_opacity(0.25)
                    for i in (0, 1, 3)], run_time=1.0)

    # ------------------------------------------------------------------ #
    # Act 5 — The Stiffest Thing in the Universe (21 s) — THE BIG ZOOM    #
    # ------------------------------------------------------------------ #

    def act5_stiffness(self):
        # Beat 35
        headline(self, "That tiny fraction is hiding a monster.", hold=0.2)

        # Beat 36 — the dive target: the denominator glyphs of the fraction
        frac = self.efe[2]
        bar = max(frac, key=lambda g: g.width)  # the fraction line spans the width
        den = VGroup(*[g for g in frac
                       if g is not bar
                       and g.get_center()[1] < bar.get_center()[1] - 0.05])
        self.play(den.animate.set_color(OLIVE_BRIGHT), run_time=1.0)

        # Beat 37 — THE BIG ZOOM: three tightening pulses; zoom 3.0, once only
        c = den.get_center()
        self.move_camera(frame_center=c, zoom=1.6, run_time=1.2)
        self.move_camera(frame_center=c, zoom=2.3, run_time=1.1)
        self.c4_halo = glow(den, color=OLIVE, layers=5)
        self.move_camera(frame_center=c, zoom=3.0, run_time=1.2,
                         added_anims=[FadeIn(self.c4_halo)])

        # Beat 38
        caption(self, "That unthinkable speed, multiplied into itself four times.",
                hold=0.9)

        # Beat 39 — c itself, small at the monolith's base
        c_val = MathTex("c", "=", "299{,}792{,}458", "\\mathrm{m/s}").scale(0.5)
        for part, col in zip(c_val, [OLIVE, IVORY, IVORY, FOG]):
            part.set_color(col)
        c_val.next_to(den, DOWN, buff=0.35)
        self.play(FadeIn(c_val), run_time=1.5)

        # Beat 40
        caption(self, "Three hundred million meters, every single second.", hold=0.9)

        # Beat 41 — the number grows out of c: thirty-three zeros of bedrock
        c4_mag = MathTex("c^{4}", "\\approx", "8.1\\times 10^{33}",
                         "\\mathrm{m^{4}/s^{4}}").scale(0.5)
        for part, col in zip(c4_mag, [OLIVE, IVORY, OLIVE_BRIGHT, FOG]):
            part.set_color(col)
        c4_mag.move_to(c_val)
        self.play(TransformMatchingTex(c_val, c4_mag), run_time=2.0)

        # Beat 42
        caption(self, "An eight followed by thirty-three more zeros — and it divides.",
                hold=1.4)

        # Beat 43 — the longest stillness in the film: not power, resistance
        self.wait(1.2)

        # Beat 44 — one breath out; the equation reassembles in full glow
        restore = [self.efe[i].animate.set_color(self._efe_colors[i]).set_opacity(1.0)
                   for i in (0, 1, 3)]
        restore.append(den.animate.set_color(OLIVE))
        self.move_camera(frame_center=ORIGIN, zoom=1.0, run_time=2.0,
                         added_anims=[FadeOut(c4_mag), FadeOut(self.c4_halo)] + restore)

        # Beat 45
        headline(self, "Spacetime is the stiffest material in existence.",
                 sub="stiff.", hold=0.5, font_size=64)

    # ------------------------------------------------------------------ #
    # Act 6 — The Song Takes Shape (26 s)                                 #
    # ------------------------------------------------------------------ #

    def act6_chirp(self):
        # Beat 46
        headline(self, "The real shape: flat, plus a whisper.", hold=0.1)

        # Beat 47 — g = eta + h, written on the mirror-flat stage
        linmet = MathTex("g_{\\mu\\nu}", "=", "\\eta_{\\mu\\nu}", "+",
                         "h_{\\mu\\nu}").scale(1.4).move_to([0, 2.2, 0])
        for part, col in zip(linmet, [CORAL, IVORY, CORAL, SKY, SKY]):
            part.set_color(col)
        self.play(Write(linmet), FadeOut(self.efe), run_time=1.7)

        # Beat 48
        caption(self, "One geometry, split for bookkeeping: flat plus a tiny ripple.",
                hold=0.9)

        # Beats 49-50 — into h itself
        self.move_camera(frame_center=linmet[4].get_center(), zoom=2.5, run_time=1.5,
                         added_anims=[p.animate.set_opacity(0.3)
                                      for p in linmet if p is not linmet[4]])
        caption(self, "h — space itself doing the waving.", color=SKY, hold=0.7)

        # Beat 51 — pull back; the metric makes room for the experiment
        self.move_camera(frame_center=ORIGIN, zoom=1.0, run_time=1.0,
                         added_anims=[FadeOut(linmet)])

        # Beat 52 — the pearl ring
        n = 24
        rest = [np.array([1.8 * np.cos(k * TAU / n), 1.8 * np.sin(k * TAU / n), 0])
                for k in range(n)]
        pearls = VGroup(*[Dot(point=p, radius=0.06, color=IVORY) for p in rest])
        h_lab = MathTex("h").scale(1.1).set_color(SKY).move_to([2.6, 1.6, 0])
        self.play(FadeIn(pearls), FadeIn(h_lab), run_time=1.5)

        # Beat 53
        caption(self, "h: how much distances stretch as the wave passes.",
                color=SKY, hold=0.8)

        # Beat 54 — two full h_+ cycles; no pearl ever moves on its own
        ph = ValueTracker(0.0)

        def ring_breathe(m):
            s = 0.175 * np.sin(ph.get_value())
            for dot, p in zip(m, rest):
                dot.move_to([p[0] * (1 + s), p[1] * (1 - s), 0])

        pearls.add_updater(ring_breathe)
        self.play(ph.animate.set_value(2 * TAU), run_time=2.8, rate_func=linear)
        pearls.clear_updaters()

        # Beat 55
        self.wait(0.7)

        # Beat 56
        headline(self, "A dying orbit writes a rising song: the chirp.",
                 hold=0.4, font_size=64)

        # Beat 57 — the death spiral, finished
        self._tau_rate = 2.0
        self.R_orb.set_value(1.4)
        self._bh_place(None)
        self.binary.add_updater(self._bh_place)
        self.add(self.waves)
        self.move_camera(
            phi=55 * DEGREES, theta=-30 * DEGREES, zoom=0.9, run_time=1.5,
            added_anims=[FadeIn(self.binary), self.wave_fade.animate.set_value(1.0),
                         FadeOut(pearls), FadeOut(h_lab),
                         self.R_orb.animate.set_value(0.35)],
        )
        self.binary.clear_updaters()
        remnant = Sphere(radius=0.55, resolution=(16, 16),
                         checkerboard_colors=["#050505", "#0b0b0a"],
                         fill_opacity=1.0).move_to([0, 0, 0.12])
        remnant.set_stroke("#141414", width=0.4, opacity=0.5)
        flash = glow_dot(point=[0, 0, 0.12], color=GOLD, radius=0.22, layers=6)
        self.play(FadeOut(self.binary), FadeIn(remnant), FadeIn(flash), run_time=0.5)
        self.play(FadeOut(flash), run_time=0.5)

        # Beat 58 — back to the flat stage as the remnant settles
        self._tau_rate = 0.0
        self.move_camera(phi=0 * DEGREES, theta=-90 * DEGREES, zoom=1.0,
                         frame_center=ORIGIN, run_time=1.0,
                         added_anims=[FadeOut(remnant),
                                      self.wave_fade.animate.set_value(0.0)])
        self.remove(self.waves)

        # Beat 59 — the chirp, drawn like a heartbeat beginning to panic
        self.chirp = ParametricFunction(
            lambda t: np.array([-6 + 12 * t, chirp_y(t), 0]),
            t_range=[0, 1, 0.001], color=SKY, stroke_width=3)
        self.htl = MathTex("h(t)").scale(0.9).set_color(SKY).move_to([-5.2, 1.6, 0])
        self.play(Create(self.chirp), FadeIn(self.htl), run_time=3.2, rate_func=linear)

        # Beat 60
        caption(self, "Cycles bunch, peaks climb, one spike, three wobbles — silence.",
                color=SKY, hold=1.3)

    # ------------------------------------------------------------------ #
    # Act 7 — The Morning We Heard It (16 s)                              #
    # ------------------------------------------------------------------ #

    def act7_morning(self):
        # Beat 61 — the date, stamped onto black
        headline(self, "SEPTEMBER 14, 2015", hold=0.2)

        # Beat 62 — the universe's copy settles over the prediction
        self.measured = ParametricFunction(
            lambda t: np.array([
                -6 + 12 * t,
                chirp_y(t) + 0.045 * np.sin(89 * t + 0.7) + 0.03 * np.sin(53 * t + 2.1),
                0,
            ]),
            t_range=[0, 1, 0.001], stroke_width=2)
        self.measured.set_stroke(IVORY, width=2, opacity=0.75)
        self.play(FadeIn(self.measured), run_time=2.2)

        # Beat 63
        caption(self, "The same curve — drawn this time by the universe.", hold=0.8)

        # Beat 64 — the number that pays off the c^4 charge
        strain = MathTex("h", "\\approx", "10^{-21}").scale(1.5).move_to([0, 0.6, 0])
        for part, col in zip(strain, [SKY, IVORY, SKY]):
            part.set_color(col)
        self.play(FadeIn(strain),
                  self.chirp.animate.set_stroke(opacity=0.25),
                  self.measured.animate.set_stroke(opacity=0.2), run_time=1.4)

        # Beat 65
        caption(self, "One part in a thousand billion billion.", color=SKY, hold=0.8)

        # Beat 66 — the strain cashes out into a ruler
        arm = MathTex("\\Delta L", "=", "h \\times L", "\\approx",
                      "4\\times 10^{-18}\\,\\mathrm{m}").scale(1.1).move_to(strain)
        for part, col in zip(arm, [OLIVE, IVORY, SKY, IVORY, OLIVE]):
            part.set_color(col)
        self.play(TransformMatchingTex(strain, arm), run_time=1.8)

        # Beat 67
        caption(self, "A thousandth of a proton, across four kilometers — and we felt it.",
                hold=1.0)

        # Beat 68 — the observatory at dawn: fabric above, voice below
        tilt = 50 * DEGREES
        monitor = RoundedRectangle(corner_radius=0.08, width=3.4, height=2.0,
                                   fill_color="#111110", fill_opacity=1.0,
                                   stroke_color=FOG, stroke_width=1.5)
        monitor.move_to([-1.8, -0.9, 0])
        mini = self.chirp.copy()
        mini.set_stroke(SKY, width=2, opacity=0.95)
        mini.scale(0.24).move_to(monitor.get_center())
        window = Rectangle(width=4.6, height=2.6, stroke_color=FOG, stroke_width=2)
        window.move_to([1.0, 0.5, 0])
        vig = VGroup(monitor, mini, window)
        vig.rotate(tilt, axis=RIGHT, about_point=ORIGIN)

        wc = _rx(np.array([1.0, 0.5, -0.35]), tilt)
        self.w_amp = ValueTracker(0.0)
        self.vig_fade = ValueTracker(0.0)

        def make_wgrid():
            a = self.w_amp.get_value()
            f = self.vig_fade.get_value()
            s = Surface(
                lambda u, v: np.array([0.55 * u, 0.28 * v,
                                       a * np.sin(1.5 * u) * np.cos(1.5 * v)]),
                u_range=[-2, 2], v_range=[-2, 2], resolution=(12, 12),
                fill_opacity=0.15 * f, checkerboard_colors=[DARK_A, DARK_B],
            )
            s.set_stroke(CORAL, width=0.8, opacity=0.5 * f)
            s.rotate(tilt, axis=RIGHT, about_point=ORIGIN)
            s.shift(wc)
            return s

        wgrid = always_redraw(make_wgrid)
        self.add(wgrid)
        cap = getattr(self, "_mythos_caption", None)
        extra = [FadeOut(cap)] if cap is not None else []
        self._mythos_caption = None
        self.move_camera(
            phi=tilt, theta=-90 * DEGREES, zoom=0.9, frame_center=ORIGIN, run_time=1.4,
            added_anims=[FadeOut(self.chirp), FadeOut(self.measured),
                         FadeOut(self.htl), FadeOut(arm), FadeIn(vig),
                         self.vig_fade.animate.set_value(1.0),
                         self.stars.animate.set_opacity(0.4)] + extra,
        )
        # the grid beyond the window trembles exactly once
        self.play(self.w_amp.animate.set_value(0.12), run_time=0.3)
        self.play(self.w_amp.animate.set_value(0.0), run_time=0.3)

        # Beat 69 — earned
        headline(self, "We heard spacetime sing.", hold=0.4)
        self.wait(0.1)
